apiVersion : apps/v1
kind: Deployment
metadata:
  name: avgkolspringazuredevopsbuiltin 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avgkolspringazuredevopsbuiltin
  template:
    metadata:
      labels:
        app: avgkolspringazuredevopsbuiltin 
    spec:
      containers:
        - name: avgkolspringazuredevopsbuiltin 
          image: anantaguha.azurecr.io/avgkolspringazuredevopsbuiltin
          ports:
          - containerPort: 8080