apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sbdemo 
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: sbdemo 
    spec:
      containers:
        - name: sbdemo 
          image: anything
          ports:
          - containerPort: 8080
